name: medypt-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13.7
  - fenics-dolfinx==0.10.0
  - gmsh==4.15.0
  - mpi4py==4.1.1
  - numpy==2.3.5
  - petsc4py==3.24.1
  - scifem==0.14.0
  - sphinx==8.3.0
  - sphinx_rtd_theme==3.0.2
prefix: /home/docs/.conda/envs/medypt-docs